name: notifee
description: A feature rich Android & iOS notifications library for Flutter.
version: 0.0.1
homepage: https://notifee.app

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  notifee_platform_interface: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.notifee
        pluginClass: NotifeePlugin
      ios:
        pluginClass: NotifeePlugin
